### ISSUE TITLE
Suggestion to reduce blockly output

### ISSUE THREAD

**Issue by pmallas** [sethoscope/heatmap#26]
Thanks for your code.  I do have one small suggestion. Perhaps inserting so code to skip zero valued data (at line 615):
      for (coord, val) in matrix.items():
            if val == 0.0:
                continue
            x = int(coord.x - extent.min.x)

I found that my output was very "blocky" without this because where the data is zero valued, a color is still assigned.  This is probably due to the color scheme I used.

**Comment by sethoscope** [comment]
FIxed with fcec30b4d673452355a62cd65347fc085fc4fd6c
I do think that any color scheme that creates a sharp discontinuity between zero and infinitesimal values is probably not a good idea, but ugly blocky output is not a good outcome regardless.
