### ISSUE TITLE
The arguments are order dependant

### ISSUE THREAD

**Issue by craigloftus** [sethoscope/heatmap#33]
Just a minor issue I noticed. The `--osm` argument works if placed at the end of the arguments, but not at the start.

**Comment by sethoscope** [comment]
I can't reproduce that (works fine when I try it). Can you give an example of a command line that doesn't work?

**Comment by craigloftus** [comment]
I've just look at my history and it was me being a fool. I had a missing hyphen the first time around. Presumably this was being interpreted as passing in the `o`, `s` and `m` options without any values.
