### ISSUE TITLE
Problem using osm

### ISSUE THREAD

**Issue by MarieCoco** [sethoscope/heatmap#39]
Hello,

I am using your heatmap code and I would like to use, like you did, the osm option. So I tried first with the same as you, the map of Orkney islands (I downloaded some other .gpx file or orkney islands). But I keep getting the following error :

Traceback (most recent call last):
  File "heatmap.py", line 1262, in <module>
    main()
  File "heatmap.py", line 1241, in main
    config.fill_missing()
  File "heatmap.py", line 1195, in fill_missing
    get_osm_background(self, padding)
  File "heatmap.py", line 754, in get_osm_background
    image, img_bbox_ll = _get_osm_image(bbox_ll, zoom, config.osm_base)
  File "heatmap.py", line 691, in _get_osm_image
    from osmviz.manager import PILImageManager, OSMManager
  File "/home/FUNDP/mcohilis/.local/lib/python3.4/site-packages/osmviz/manager.py", line 60
    raise Exception, "UNIMPLEMENTED"
                   ^
SyntaxError: invalid syntax

Here is my command line :
python3 heatmap.py -o orkney.png --extent=58.7,-2.5,59.8,-2 --height 800 --osm orkney.gpx

So it seems like there is a syntax error in osmviz package? Seems weird. I also tried with your other example (photo-points) and I get the same error. 
Do you know something about it?

Thanks a lot in advance,

Marie

**Comment by sethoscope** [comment]
osmviz doesn't currently support Python 3.  I submitted [a patch](https://github.com/cbick/osmviz/pull/6) yesterday to fix that. In the meantime, you can either use Python 2 or use my version of osmviz; the relevant updated file is here:
https://github.com/sethoscope/osmviz/blob/2to3/src/osmviz/manager.py

**Comment by hugovk** [comment]
My fork has recently had support for Python 3 added: https://github.com/hugovk/osmviz

It's also the one that's on PyPI, so I'll make a new release that includes this.

**Comment by hugovk** [comment]
This is now released on PyPI as osmviz 1.1.0: `pip install -U osmviz`
