### ISSUE TITLE
Is there a possibility to pass dir as input?

### ISSUE THREAD

**Issue by alessss** [sethoscope/heatmap#46]
Hi!
Thanks for cool script!
I have a question: i have milions of lines with coordinates in different csv files, so I can't merge them into one csv file. Is there a possibility to give dir name as input, but not exact csv file?

Thanks,
Alex.

**Comment by sethoscope** [comment]
No, but you can give it lots of input files. For example,
`heatmap.py -o map.png --width 100 *.csv`

**Comment by alessss** [comment]
python heatmap.py -W 5000 -H 5000 -o test_night.jpeg --csv *.csv --osm -d 0.8 -r 2 - takes only one file

**Comment by hugovk** [comment]
Try without --csv. See: 

https://github.com/sethoscope/heatmap/blob/master/CMDLINE_UPDATING.md

**Comment by alessss** [comment]
Got trace trying to generate jpeg.

```
Traceback (most recent call last):
  File "../../heatmap/heatmap.py", line 1263, in <module>
    main()
  File "../../heatmap/heatmap.py", line 1251, in main
    image.save(args.output)
  File "/Users/a_makarevich/.venvs/heatmap/lib/python2.7/site-packages/PIL/Image.py", line 1930, in save
    save_handler(self, fp, filename)
  File "/Users/a_makarevich/.venvs/heatmap/lib/python2.7/site-packages/PIL/JpegImagePlugin.py", line 607, in _save
    raise IOError("cannot write mode %s as JPEG" % im.mode)
IOError: cannot write mode RGBA as JPEG
```

**Comment by hugovk** [comment]
Try output to png instead of jpeg.

It's attempting to save with transparency, and jpeg doesn't do transparency.
