### ISSUE TITLE
Openstreetmap function broken; easy fix

### ISSUE THREAD

**Issue by gitsmol** [sethoscope/heatmap#63]
The --osm flag results in an error. This is because the osmviz library has deprecated OSMManager.createOSMImage in favor of OSMManager.create_osm_image.

Change line 702 to:
`        image, bounds = osm.create_osm_image((c1.lat, c2.lat, c1.lon, c2.lon),`

and it is fixed.

**Comment by hugovk** [comment]
Will be fixed by https://github.com/sethoscope/heatmap/pull/62.

**Comment by hugovk** [comment]
#62 has been fixed, this can be closed.
